python sample.py \
    --model_path saved_models/bba \
    --gen_mode om_interpolate \
    --flow_matching \
    --num_samples_eval 2 \
    --batch_size_gen 2 \
    --latent_time 1 \
    --initial_guess_level 8 \
    --subsample_points_percent 1.0 \
    --subsample_dimensions_percent 1.0 \
    --no_encode_and_decode \
    --action truncated \
    --optimizer adam \
    --lr 2e-1 \
    --append_exp_name test \
    --path_length 200 \
    --om_d 0.1 \
    --steps 2000