python sample.py \
    --model_path saved_models/trp_cage \
    --gen_mode om_interpolate \
    --num_samples_eval 4 \
    --batch_size_gen 1 \
    --latent_time 15 \
    --initial_guess_level 250 \
    --subsample_points_percent 1.0 \
    --subsample_dimensions_percent 1.0 \
    --no_encode_and_decode \
    --action truncated \
    --optimizer adam \
    --lr 2e-1 \
    --append_exp_name test_initial_latent_time_250_higher_dt \
    --path_length 200 \
    --om_dt 1.0 \
    --om_d 0.1 \
    --steps 1000