python sample.py \
    --model_path saved_models/chignolin \
    --gen_mode om_interpolate \
    --num_samples_eval 8 \
    --batch_size_gen 8 \
    --latent_time 20 \
    --initial_guess_level 250 \
    --no_encode_and_decode \
    --append_exp_name test \
    --path_length 200 \
    --steps 20 \
    --disable_logging