python sample.py \
    --model_path saved_models/trp_cage \
    --gen_mode om_interpolate \
    --num_samples_eval 8 \
    --batch_size_gen 8 \
    --latent_time 15 \
    --initial_guess_level 0 \
    --no_encode_and_decode \
    --append_exp_name test_initial_latent_time=0_mlff \
    --mlff \
    --om_dt 0.01 \
    --path_length 200 \
    --steps 2000 \