python sample.py \
    --model_path saved_models/tetrapeptides \
    --gen_mode iid \
    --data_folder /data/sanjeevr/4AA_data \
    --num_samples_eval 1000 \
    --batch_size_gen 1000 \
    --latent_time 0.6 \
    --initial_guess_level 8 \
    --subsample_points_percent 1.0 \
    --subsample_dimensions_percent 1.0 \
    --no_encode_and_decode \
    --action truncated \
    --optimizer adam \
    --lr 2e-1 \
    --append_exp_name test_latent_time=0.6 \
    --path_length 200 \
    --om_d 0.1 \
    --steps 2000