import argparse
import json
import torch
from torch_scatter import scatter_mean
import numpy as np
import mdtraj as md
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from os.path import join
from deeptime.clustering import MiniBatchKMeans
from deeptime.markov import TransitionCountEstimator, pcca
from sklearn.preprocessing import normalize
import seaborn as sns
from scipy.spatial.distance import jensenshannon
from pathlib import Path
import os
import sys
from rmsd import kabsch_rotate

sys.path.insert(0, "")
from evaluate.evaluators import (
    PwdEvaluator,
    TicEvaluator,
    RmsdEvaluator,
    ContactEvaluator,
    get_pwd_triu_batch,
    js_divergence,
)
from actions import S2Action, TruncatedAction, SimpleAction
from utils import center_zero
from evaluate.msm_utils import (
    find_min_flux_states,
    discretize_trajectory,
    sample_tp,
    get_tp_likelihood,
    compute_shannon_entropy,
)

from datasets.dataset_utils_empty import Molecules
from logging_utils import get_interpolation_viz, visualize_gif, save_ovito_traj
from IPython.display import Image as IPImage, display
from PIL import Image
from tqdm import tqdm
from collections import defaultdict
import heapq
from matplotlib.colors import ListedColormap

# default cluster endpoints for testing interpolation (obtained by visual inspection of what are hard transition paths to capture)
CLUSTER_ENDPOINTS = {
    "chignolin": [5, 17],
    "trp_cage": [14, 13],
    "bba": [18, 3],
    "villin": [13, 6],
    "protein_g": [17, 2],
}

start_tica_coords = {
    "chignolin": np.array([-0.5, 0]),
    "trp_cage": np.array([-2.2, 0]),
    "protein_g": np.array([-0.75, 0]),
}

end_tica_coords = {
    "chignolin": np.array([1.6, 0.1]),
    "trp_cage": np.array([0.5, 2.5]),
    "protein_g": np.array([1.75, -2]),
}

# Preset cluster centers, determined via standard K-means clustering
# (elbow method to find the number fo clusters)
num_clusters_per_protein = {
    "chignolin": 3,
    "villin": 3,
    "trp_cage": 3,
    "bba": 4,
}

cluster_centers = {
    "chignolin": np.array(
        [[0.69400153, -0.34598462], [-0.48732213, 0.00642035], [1.87483537, 0.06285344]]
    ),
    "trp_cage": np.array(
        [[-2.15921372, 0.0062795], [0.47752285, -0.38050238], [0.40182245, 2.0690773]]
    ),
    "bba": np.array(
        [
            [-0.5756589, -0.60663654],
            [1.7861676, -0.87717611],
            [0.91295128, 1.07518898],
            [-0.49210152, 0.40313689],
        ]
    ),
    "villin": np.array(
        [
            [1.08971813, -0.98522752],
            [-2.49001353, -2.31375028],
            [-0.12929561, 0.53703407],
        ]
    ),
}

ref_time = {
    "chignolin": 20,
    "bba": 5,
    "trp_cage": 15,
    "villin": 5,
    "protein_g": 5,
}


def evaluate_fastfolders(
    protein_name,
    gen_mode,
    append_exp_name,
    sim=0,
    subsample=None,
    window_size=3,
    gif=True,
    model=None,
    num_paths=8,
):
    """
    Top-level function to evaluate the samples/interpolation paths generated by the model.
    """
    # Set the random seed for reproducibility of k-means clustering
    np.random.seed(0)

    append_exp_name_str = "_" + append_exp_name if append_exp_name else ""
    eval_folder = (
        f"saved_models/{protein_name}/main_eval_output_{gen_mode}{append_exp_name_str}"
    )

    # Define starting and ending states for interpolation
    start = CLUSTER_ENDPOINTS[protein_name][0]
    end = CLUSTER_ENDPOINTS[protein_name][1]

    # First, do dynamics analysis to get Markov State Model parameters
    # TODO: eventually replace this with precomputed values on the reference simulation (instead of Langevin)
    (
        prob_matrix,
        kmeans_cluster_centers,
        tic_evaluator,
        ref_dihedrals,
        ref_pwds,
    ) = dynamics_analysis(
        protein_name,
        "langevin",
        append_exp_name=None,
        num_clusters=20,
        subsample=None,
    )

    # Then, find the most probable path between the start and end states
    path = most_probable_path(prob_matrix, start, end)
    path = [i - 1 for i in path]  # Convert back to zero indexing
    path_centers = kmeans_cluster_centers[path]

    # Load data
    append_exp_name_str = "_" + append_exp_name if append_exp_name else ""
    eval_folder = (
        f"saved_models/{protein_name}/main_eval_output_{gen_mode}{append_exp_name_str}"
    )
    sample_path = Path(eval_folder, f"sample-{gen_mode}.pt")
    pdb_file = (
        f"datasets/folded_pdbs/{Molecules[protein_name.upper()].value}-0-c-alpha.pdb"
    )
    # Load sampled molecules
    sampled_mol = torch.load(sample_path)
    if subsample is not None:
        sampled_mol = sampled_mol[subsample]
    n_atoms = sampled_mol.shape[1]

    # Load topology from pdb file
    topology = md.load(pdb_file).topology

    # Discretize the interpolation trajectory based on the reference cluster centers
    cluster_assignments = discretize_trajectory(
        sampled_mol, tic_evaluator, kmeans_cluster_centers
    )

    # Create MSM with 20 states
    interpolation_prob_matrix = TransitionCountEstimator.count(
        count_mode="sliding", dtrajs=[cluster_assignments.astype("int")], lagtime=1
    )
    interpolation_prob_matrix = normalize(interpolation_prob_matrix, axis=1, norm="l1")

    # Sample transition paths from the constructed MSM
    n_samples = 1000
    traj_len = 10
    sampled_traj = sample_tp(
        interpolation_prob_matrix, start - 1, end - 1, traj_len, n_samples
    )
    ref_sampled_traj = sample_tp(prob_matrix, start - 1, end - 1, traj_len, n_samples)

    # Compute entropy of the sampled trajectories (proxy for diversity)
    entropy = compute_shannon_entropy(sampled_traj)
    ref_entropy = compute_shannon_entropy(ref_sampled_traj)

    # Compute JSD between the state distributions of the reference and generated paths
    sampled_state_dist = np.array(
        [np.count_nonzero(sampled_traj == i) for i in range(20)]
    )
    sampled_state_dist = sampled_state_dist / sampled_state_dist.sum()
    ref_state_dist = np.array(
        [np.count_nonzero(ref_sampled_traj == i) for i in range(20)]
    )
    ref_state_dist = ref_state_dist / ref_state_dist.sum()
    jsd = jensenshannon(ref_state_dist, sampled_state_dist)

    # Compute the likelihood of the sampled trajectories under the reference MSM
    path_probabilities = get_tp_likelihood(sampled_traj, prob_matrix).prod(-1)

    # Percentage of valid (non-zero probability) paths
    fraction_valid_paths = (
        path_probabilities[path_probabilities > 0].shape[0]
        / path_probabilities.shape[0]
    )

    # JSD between the reference and generated state distributions

    # Finally, visualize the model-produced interpolation along with the reference (most probable) path
    free_energies, fraction_unphysical = get_tic_free_energy_plots(
        protein_name,
        gen_mode,
        append_exp_name,
        subsample,
        ref_path=path_centers,
        gif=True,
        window_size=window_size,
        num_paths=num_paths,
        ref_dihedrals=ref_dihedrals,
        ref_pwds=ref_pwds,
    )

    # Save final metrics to a JSON file
    max_free_energies = np.array(
        [np.max(free_energy_profile) for free_energy_profile in free_energies]
    )
    metrics = {
        "Max Free Energy (kBT) Mean: ": max_free_energies.mean(),
        "Max Free Energy (kBT) Std: ": max_free_energies.std(),
        "Fraction of Physical Paths": 1 - fraction_unphysical,
        "Path Probability Mean": path_probabilities.mean(),
        "Path Probability Std": path_probabilities.std(),
        "Fraction of Valid Paths": fraction_valid_paths,
        "Jensen-Shannon Divergence of State Distributions": jsd,
        "Transition Path Entropy (Diversity)": entropy,
        "Reference Transition Path Entropy (Diversity)": ref_entropy,
    }
    # TODO: other metrics to add:
    # 1. Probablity of paths under the reference MSM (mean and std)
    # 2. Percentage of valid (non-zero probability) paths
    # 3. JS divergence of state distributions between the reference and generated paths (mean and std)
    # 4. Diversity of the generated paths (average pairwise RMSD)
    with open(join(eval_folder, "final_metrics.json"), "w") as f:
        json.dump(metrics, f, indent=4)  # Add indent for better readability


def get_tic_free_energy_plots(
    protein_name,
    gen_mode,
    append_exp_name,
    subsample=None,
    ref_path=None,
    window_size=7,
    gif=False,
    num_paths=8,
    ref_dihedrals=None,
    ref_pwds=None,
):
    """
    Produces a TIC plot of the samples generated by the model, along with a reference interpolation path if provided.
    Also produces a free energy curve along the generated interpolation path.
    If gif is set to True, it will create a GIF of the Onsager-Machlup optimization process.
    """

    # Load data
    append_exp_name_str = "_" + append_exp_name if append_exp_name else ""
    eval_folder = (
        f"saved_models/{protein_name}/main_eval_output_{gen_mode}{append_exp_name_str}"
    )
    sample_path = Path(eval_folder, f"sample-{gen_mode}.pt")
    pdb_file = (
        f"datasets/folded_pdbs/{Molecules[protein_name.upper()].value}-0-c-alpha.pdb"
    )
    # Load sampled molecules
    sampled_mol = torch.load(sample_path)
    if subsample is not None:
        sampled_mol = sampled_mol[subsample]
    n_atoms = sampled_mol.shape[1]

    # Load topology from pdb file
    topology = md.load(pdb_file).topology
    # print(f"Atoms: {[a for a in topology.atoms]}")

    # store endpoints if interpolation is used
    if "interpolate" in gen_mode:
        endpoints = sampled_mol.reshape(num_paths, -1, n_atoms, 3)[
            :, [0, -1]
        ].numpy()  # [num_paths, 2, n_atoms, 3]

    # Initialize evaluator
    tic_evaluator = TicEvaluator(
        val_data=None,
        mol_name=protein_name,
        eval_folder=eval_folder,
        data_folder="datasets",
        folded_pdb_folder="datasets/folded_pdbs",
        bins=101,
        evalset="testset",
    )  # The evalset is the set we'll compare to in the next evaluation steps

    loop = [sampled_mol]
    # Load path along optimization if OM interpolation is used
    if gif and gen_mode == "om_interpolate":
        path_history = Path(eval_folder, f"path_history-{gen_mode}.pt")
        path_history = torch.load(path_history)
        loop = path_history

    # Compute and save reference TIC plot
    ref_fig = tic_evaluator._plot_tic(
        tic_evaluator.gt_prob,
        endpoints=endpoints if "interpolate" in gen_mode else None,
        ref_path=ref_path,
        file_name=join(tic_evaluator.plots_folder, "TICA_reference.png"),
        title="Reference testset",
        save_plot=True,
    )

    free_energies = []

    # Create a folder to temporarily store the images if it doesn't exist
    gif_folder = "temp_gif_images"
    os.makedirs(gif_folder, exist_ok=True)

    tic_paths = []  # To keep track of the TIC image paths for creating a GIF
    free_energy_paths = (
        []
    )  # To keep track of the free energy image paths for creating a GIF
    dihedral_hist_paths = (
        []
    )  # To keep track of the dihedral angle histograms for creating a GIF
    pwd_hist_paths = (
        []
    )  # To keep track of the pairwise distance histograms for creating a GIF

    for i, path in tqdm(enumerate(loop)):
        # Get samples TIC free energy landscape
        dihedrals, pwds = tic_evaluator.get_tic_features(
            path, tic_evaluator.folded, separate=True
        )

        sample_tic_features = np.hstack((dihedrals, pwds))
        transformed_samples = tic_evaluator.tica(sample_tic_features)

        # Plot dihedral angle histogram
        plt.figure()
        plt.hist(
            np.ravel(dihedrals), bins=100, density=True, label="Interpolation Path"
        )
        if ref_dihedrals is not None:
            plt.hist(
                np.ravel(ref_dihedrals),
                bins=100,
                density=True,
                alpha=0.5,
                label="Reference",
            )
        plt.legend()
        plt.title(f"Step {i}: Dihedral angular distribution function")

        plt.xlabel("Dihedral angle (radians)")
        plt.ylabel("Frequency")
        plt.ylim(0, 0.6)
        plt.show()
        file_name = join(gif_folder, f"dihedral_{i}.png")
        plt.savefig(file_name)
        plt.close()
        dihedral_hist_paths.append(file_name)

        # Plot pairwise distance histogram
        plt.figure()
        plt.hist(np.ravel(pwds), bins=100, density=True, label="Interpolation Path")
        if ref_pwds is not None:
            plt.hist(
                np.ravel(ref_pwds), bins=100, density=True, alpha=0.5, label="Reference"
            )
        plt.legend()
        plt.title(f"Step {i}: Pairwise distance distribution function")

        plt.xlabel("Pairwise distance (Angstroms)")
        plt.ylabel("Frequency")
        plt.ylim(0, 0.2)
        plt.show()
        file_name = join(gif_folder, f"pwd_{i}.png")
        plt.savefig(file_name)
        plt.close()
        pwd_hist_paths.append(file_name)

        if i == len(loop) - 1:

            pwds = pwds.reshape(num_paths, -1, pwds.shape[-1])
            pwd_mins = np.min(pwds, axis=(1, 2))
            path_is_unphysical = np.where(pwd_mins < 0.5)[0]
            fraction_unphysical = path_is_unphysical.sum() / num_paths

        # Find the bins of the samples
        bins_x = np.digitize(transformed_samples[:, 0], tic_evaluator.bin_edges_x)
        bins_y = np.digitize(transformed_samples[:, 1], tic_evaluator.bin_edges_y)
        # clip the bins to the maximum bin index
        bins_x = np.clip(bins_x, 0, tic_evaluator.bins - 1)
        bins_y = np.clip(bins_y, 0, tic_evaluator.bins - 1)

        # probabilities of the samples as a function of path position
        gt_probs = np.zeros((path.shape[0],))

        # probabilities of the samples as a function of TICA bins
        prob_samp = np.zeros((tic_evaluator.bins, tic_evaluator.bins))

        padding = window_size // 2
        # Iterate over path
        for t in range(path.shape[0]):
            # Get the bin indices
            x_bin = bins_x[t]
            y_bin = bins_y[t]

            if tic_evaluator.gt_prob[x_bin, y_bin] != 0:
                # Ground truth probability in this bin is non-zero
                gt_probs[t] = tic_evaluator.gt_prob[x_bin, y_bin]
                prob_samp[x_bin, y_bin] = tic_evaluator.gt_prob[x_bin, y_bin]

            else:
                # Define the window boundaries
                x_min = max(0, x_bin - padding)
                x_max = min(tic_evaluator.gt_prob.shape[0] - 1, x_bin + padding)
                y_min = max(0, y_bin - padding)
                y_max = min(tic_evaluator.gt_prob.shape[1] - 1, y_bin + padding)

                # Extract the window
                window = tic_evaluator.gt_prob[x_min : x_max + 1, y_min : y_max + 1]

                # Find the minimum non-zero probability in the window
                non_zero_probs = window[window > 0]

                if non_zero_probs.size > 0:
                    # Set the minimum non-zero value in gt_probs
                    gt_probs[t] = np.min(non_zero_probs)
                    prob_samp[x_bin, y_bin] = np.min(non_zero_probs)
                else:
                    # If no non-zero values found, set gt_probs to 0
                    gt_probs[t] = 0
                    prob_samp[x_bin, y_bin] = 0

        # Calculate and plot the TIC landscape
        file_name = join(gif_folder, f"TICA_sampled_{i}.png")
        tic_evaluator._plot_tic(
            prob_samp,
            endpoints=endpoints if "interpolate" in gen_mode else None,
            path=transformed_samples if gen_mode == "langevin" else None,
            ref_path=ref_path,
            file_name=file_name,
            title="Samples",
            save_plot=True,
        )  # Save the plot

        tic_paths.append(file_name)

        # Calculate and plot the free energy profile along the path
        free_energy_profile = -np.log(gt_probs + np.exp(-10))
        free_energies.append(free_energy_profile)
        plt.figure()
        # plot free energy profile of all paths
        for profile in torch.tensor(free_energy_profile).chunk(num_paths):
            plt.plot(profile)
        plt.ylim(-6, 11)
        plt.xlabel("Path Step")
        plt.ylabel("Free energy / kBT")
        plt.title(f"Step {i}: Transition free energy profile: {protein_name}")
        plt.axhline(10, color="red", linestyle="--", label="Zero Probability Threshold")
        plt.legend()
        plt.show()
        file_name = join(gif_folder, f"free_energy_{i}.png")
        plt.savefig(file_name)
        plt.close()
        free_energy_paths.append(file_name)

    # Create a GIF from the saved TICA images
    tica_gif_path = join(tic_evaluator.plots_folder, "tica_samples.gif")
    images = [Image.open(tic_path) for tic_path in tic_paths]

    # Save as GIF
    images[0].save(
        tica_gif_path,
        save_all=True,
        append_images=images[1:],
        optimize=False,
        duration=100,  # Duration for each frame in milliseconds
        loop=0,  # Loop forever
    )

    # Repeat for the free energy images
    free_energy_gif_path = join(tic_evaluator.plots_folder, "free_energy.gif")
    images = [Image.open(free_energy_path) for free_energy_path in free_energy_paths]

    # Save as GIF
    images[0].save(
        free_energy_gif_path,
        save_all=True,
        append_images=images[1:],
        optimize=False,
        duration=100,  # Duration for each frame in milliseconds
        loop=0,  # Loop forever
    )

    # Repeat for the dihedral angle histograms
    dihedral_hist_gif_path = join(tic_evaluator.plots_folder, "dihedral_hist.gif")
    images = [
        Image.open(dihedral_hist_path) for dihedral_hist_path in dihedral_hist_paths
    ]
    images[0].save(
        dihedral_hist_gif_path,
        save_all=True,
        append_images=images[1:],
        optimize=False,
        duration=100,  # Duration for each frame in milliseconds
        loop=0,  # Loop forever
    )

    # Repeat for the pairwise distance histograms
    pwd_hist_gif_path = join(tic_evaluator.plots_folder, "pwd_hist.gif")
    images = [Image.open(pwd_hist_path) for pwd_hist_path in pwd_hist_paths]
    images[0].save(
        pwd_hist_gif_path,
        save_all=True,
        append_images=images[1:],
        optimize=False,
        duration=100,  # Duration for each frame in milliseconds
        loop=0,  # Loop forever
    )

    # Remove the temporary image files
    for image_path in (
        tic_paths + free_energy_paths + dihedral_hist_paths + pwd_hist_paths
    ):
        os.remove(image_path)

    return free_energies, fraction_unphysical


def dynamics_analysis(
    protein_name, gen_mode, append_exp_name, num_clusters=None, subsample=None
):
    """
    Analyze the dynamics of a set of samples generated by the model.
    Create a Markov State Model (MSM) by clustering the samples in TIC-space and counting the transitions between clusters.
    Returns the transition probability matrix and the cluster centers.
    """
    assert (
        gen_mode == "langevin"
    ), "Dynamics analysis is only for Langevin dynamics samples (see Note 2 above)"
    # Load data
    if num_clusters is None:
        num_clusters = num_clusters_per_protein[protein_name]

    # Inferred
    append_exp_name_str = "_" + append_exp_name if append_exp_name else ""
    eval_folder = (
        f"saved_models/{protein_name}/main_eval_output_{gen_mode}{append_exp_name_str}"
    )
    sample_path = Path(eval_folder, f"sample-{gen_mode}.pt")
    pdb_file = (
        f"datasets/folded_pdbs/{Molecules[protein_name.upper()].value}-0-c-alpha.pdb"
    )
    try:
        # Load sampled molecules
        sampled_mol = torch.load(sample_path)
    except FileNotFoundError:
        raise RuntimeError(
            f"File not found: {sample_path}. Have you run Langevin simulations for {protein_name}?"
        )

    if subsample is not None:
        sampled_mol = sampled_mol[subsample]
    # print(f"Size of samples set (num_samples x num_backbone_atoms x 3): {sampled_mol.shape}")
    n_atoms = sampled_mol.shape[1]

    # Load topology from pdb file
    topology = md.load(pdb_file).topology

    # Since we need to do K-means clustering in TIC-space, we will transform the samples first
    # (this code is the same as in the "TIC analysis" section)

    # Initialize TIC evaluator
    tic_evaluator = TicEvaluator(
        val_data=None,
        mol_name=protein_name,
        eval_folder=eval_folder,
        data_folder="datasets",
        folded_pdb_folder="datasets/folded_pdbs",
        bins=101,
        evalset="testset",
    )  # The evalset is the set we'll compare to in the next evaluation steps

    # Get samples TIC free energy landscape
    dihedrals, pwds = tic_evaluator.get_tic_features(
        sampled_mol, tic_evaluator.folded, separate=True
    )

    sample_tic_features = np.hstack((dihedrals, pwds))
    transformed_samples = tic_evaluator.tica(sample_tic_features)

    # Plot each TIC dimension as a function of time
    plt.figure()
    plt.plot(transformed_samples[:, 0], label="TIC 0")
    plt.plot(transformed_samples[:, 1], label="TIC 1")
    plt.xlabel("Time")
    plt.ylabel("TIC Value")
    plt.title("TIC Values Over Time")
    plt.legend()
    plt.savefig(join(eval_folder, f"tic_vs_time.png"))

    # K-means clustering
    kmeans = MiniBatchKMeans(
        n_clusters=num_clusters,
        max_iter=0,
        batch_size=64,
        init_strategy="kmeans++",
        n_jobs=16,
        tolerance=1e-7,
    )

    assignments = kmeans.fit_transform(transformed_samples)

    # Create MSM with 20 states
    count_matrix = TransitionCountEstimator.count(
        count_mode="sliding", dtrajs=[assignments.astype("int")], lagtime=1
    )
    count_matrix = normalize(count_matrix, axis=1, norm="l1")

    # TODO: this should only be done for the reference MSM
    start_cluster_idx, end_cluster_idx = find_min_flux_states(count_matrix)
    np.save(
        f"./evaluate/saved_references/saved_cluster_endpoints_{protein_name.upper()}.npy",
        np.array([start_cluster_idx, end_cluster_idx]),
    )

    # count_matrix = make_reversible(count_matrix)

    # # Coarse-grain the MSM to 10 states
    # pcca_msm = pcca(count_matrix, 10)

    kmeans_cluster_centers = kmeans._model.cluster_centers

    np.save(
        f"./evaluate/saved_references/saved_cluster_centers_{protein_name.upper()}.npy",
        kmeans_cluster_centers,
    )
    # kmeans_cluster_assignments = np.argmin(np.linalg.norm(transformed_samples[:, None] - kmeans_cluster_centers, axis=-1), axis=-1)

    # pcca_cluster_assignments = pcca_msm.assignments[kmeans_cluster_assignments]

    # distance_to_clusters = np.linalg.norm(
    #     transformed_samples - kmeans_cluster_centers[kmeans_cluster_assignments], axis=-1
    # )
    # cluster_rep_idxs = [
    #     np.argmin(distance_to_clusters[kmeans_cluster_assignments == i], axis=0)
    #     for i in range(kmeans_cluster_centers.shape[0])
    # ]
    # cluster_rep_coords = np.stack(
    #     [
    #         sampled_mol[kmeans_cluster_assignments == i][idx]
    #         for i, idx in enumerate(cluster_rep_idxs)
    #     ]
    # )

    return count_matrix, kmeans_cluster_centers, tic_evaluator, dihedrals, pwds


def most_probable_path(transition_matrix, start_state, end_state):
    """
    Compute the most probable path between two states in a Markov chain using Dijkstra's algorithm.
    start_state and end_state are 1-indexed.
    """
    N = len(transition_matrix)
    # convert to zero indexing
    start_state -= 1
    end_state -= 1

    # Convert the problem to a shortest path problem by taking -log of probabilities
    log_transition_matrix = -np.log(
        transition_matrix + 1e-10
    )  # Adding a small epsilon to avoid log(0)

    # Dijkstra's algorithm initialization
    min_heap = [
        (0, start_state, [])
    ]  # (current log probability, current state, path taken)
    visited = set()

    while min_heap:
        current_log_prob, current_state, path = heapq.heappop(min_heap)

        # If we've already visited this state, skip it
        if current_state in visited:
            continue

        # Mark the current state as visited
        visited.add(current_state)

        # Include the current state in the path
        path = path + [current_state]

        # If we've reached the end state, return the path
        if current_state == end_state:
            return [path + 1 for path in path]  # Convert back to 1-indexing

        # Explore neighbors
        for next_state in range(N):
            if next_state not in visited:
                new_log_prob = (
                    current_log_prob + log_transition_matrix[current_state][next_state]
                )
                heapq.heappush(min_heap, (new_log_prob, next_state, path))

    # If no path is found
    return []


def compute_path_probability(transition_matrix, path):
    """
    Compute the probability of a path in a Markov chain.
    path is 0-indexed.
    """
    probability = 1.0
    for i in range(len(path) - 1):
        current_state = path[i]
        next_state = path[i + 1]
        probability *= transition_matrix[current_state][next_state]
    return probability


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--protein_name",
        type=str,
        default="chignolin",
        help="Name of the protein to evaluate",
    )
    parser.add_argument(
        "--gen_mode",
        type=str,
        default="om_interpolate",
        help="Generation mode (iid, langevin, interpolate, om_interpolate)",
    )
    parser.add_argument(
        "--append_exp_name",
        type=str,
        default=None,
        help="Append experiment name to the saved model folder",
    )
    parser.add_argument(
        "--sim",
        type=int,
        default=0,
        help="Simulation number (0-100) to evaluate",
    )

    args = parser.parse_args()

    evaluate_fastfolders(
        args.protein_name, args.gen_mode, args.append_exp_name, args.sim
    )
