import argparse
import json
from datetime import datetime
import torch
import wandb
from torch_scatter import scatter_mean
import numpy as np
import mdtraj as md
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from os.path import join
from deeptime.clustering import MiniBatchKMeans
from deeptime.markov import TransitionCountEstimator, pcca
from sklearn.preprocessing import normalize
import seaborn as sns
from scipy.spatial.distance import jensenshannon
from pathlib import Path
import os
import sys
import math
from rmsd import kabsch_rotate
from IPython.display import Image as IPImage, display
from PIL import Image
from tqdm import tqdm
from collections import defaultdict
import heapq
from matplotlib.colors import ListedColormap

sys.path.insert(0, "")

from models import CommittorNN, GraphTransformer

from evaluate.evaluators import (
    PwdEvaluator,
    TicEvaluator,
    RmsdEvaluator,
    ContactEvaluator,
    get_pwd_triu_batch,
    js_divergence,
)

from evaluate.msm_utils import (
    find_min_flux_states,
    discretize_trajectory,
    sample_tp,
    get_tp_likelihood,
    compute_shannon_entropy,
)

from datasets.dataset_utils_empty import (
    Molecules,
    AtomSelection,
    DEShawDataset,
    to_angstrom,
    norm_stds,
)

from actions import S2Action, TruncatedAction, SimpleAction
from utils import center_zero
from logging_utils import get_interpolation_viz, visualize_gif, save_ovito_traj


# default cluster endpoints for testing interpolation
# (obtained by visual inspection of what are hard transition paths to capture)
CLUSTER_ENDPOINTS = {
    "chignolin": [11, 13],
    "trp_cage": [2, 13],
    "bba": [9, 17],
    "villin": [0, 17],
    "protein_g": [11, 14],
}


def evaluate_fastfolders(
    protein_name,
    gen_mode,
    append_exp_name,
    subsample=0,
    window_size=3,
    gif=True,
    model=None,
    num_paths=8,
    endpoints=None,
    log=False,
):
    """
    Top-level function to evaluate the samples/interpolation paths generated by various methods.
    """
    # Set the random seed for reproducibility of k-means clustering
    np.random.seed(0)

    # Adjust number of paths for iid and langevin generation
    if "interpolate" not in gen_mode:
        num_paths = 1

    append_exp_name_str = "_" + append_exp_name if append_exp_name else ""
    eval_folder = (
        f"saved_models/{protein_name}/main_eval_output_{gen_mode}{append_exp_name_str}"
    )

    # Load the reference dataset
    dataset = DEShawDataset(
        data_root="/data/sanjeevr/Reference_MD_Sims",
        molecule=Molecules[protein_name.upper()],
        simulation_id=0,
        atom_selection=AtomSelection.A_CARBON,
        return_bond_graph=False,
        transform=to_angstrom,
        align=False,
    )

    gt_traj = 10 * dataset.traj.xyz  # convert to angstroms
    gt_traj -= gt_traj.mean(1, keepdims=True)  # center

    # Define starting and ending states for interpolation
    if endpoints is not None:
        start, end = endpoints
    else:
        cluster_endpoints_path = Path(
            os.path.join(
                "evaluate",
                "saved_references",
                f"saved_cluster_endpoints_{protein_name.upper()}.npy",
            )
        )

    ref_dihedral_path = Path(
        os.path.join(
            "evaluate",
            "saved_references",
            f"saved_dihedrals_{protein_name.upper()}.npy",
        )
    )
    if ref_dihedral_path.exists():
        ref_dihedrals = np.load(ref_dihedral_path)
        gt_prob_matrix = np.load(
            f"./evaluate/saved_references/saved_transition_matrix_{protein_name.upper()}.npy"
        )

        kmeans_cluster_centers = np.load(
            f"./evaluate/saved_references/saved_cluster_centers_{protein_name.upper()}.npy"
        )
        ref_pwds = np.load(
            f"./evaluate/saved_references/saved_pwds_{protein_name.upper()}.npy"
        )

    else:
        # Compute the necessary values from the reference simulation data
        print("Computing reference values...")
        (
            gt_prob_matrix,
            kmeans_cluster_centers,
            ref_dihedrals,
            ref_pwds,
        ) = dynamics_analysis(
            protein_name,
            "NONE",
            append_exp_name=None,
            num_clusters=20,
            subsample=None,
            gt_traj=gt_traj,
        )
    if endpoints is None:
        # cluster_endpoints = np.load(cluster_endpoints_path)
        cluster_endpoints = CLUSTER_ENDPOINTS[protein_name]
        start, end = cluster_endpoints[0], cluster_endpoints[1]

    # Get TIC evaluator
    tic_evaluator = TicEvaluator(
        val_data=None,
        mol_name=protein_name,
        eval_folder=eval_folder,
        data_folder="datasets",
        folded_pdb_folder="datasets/folded_pdbs",
        bins=101,
        evalset="testset",
    )

    # Load data
    append_exp_name_str = "_" + append_exp_name if append_exp_name else ""
    eval_folder = (
        f"saved_models/{protein_name}/main_eval_output_{gen_mode}{append_exp_name_str}"
    )
    sample_path = Path(eval_folder, f"sample-{gen_mode}.pt")
    pdb_file = (
        f"datasets/folded_pdbs/{Molecules[protein_name.upper()].value}-0-c-alpha.pdb"
    )
    # Load sampled molecules
    sampled_mol = torch.load(sample_path)
    if subsample != 0:
        sampled_mol = sampled_mol[:subsample]
    n_atoms = sampled_mol.shape[1]

    # Load topology from pdb file
    topology = md.load(pdb_file).topology

    # Load committor probabilities
    committor_probs_file = (
        f"evaluate/saved_references/{protein_name}_committor_probs_{start}_{end}.npy"
    )
    bin_committor_probs = np.load(committor_probs_file)

    # Load GT transition ensemble TIC coordinates
    gt_transition_ensemble_file = f"./evaluate/saved_references/{protein_name}_{start}_{end}_transition_ensemble_TICA.npy"
    gt_transition_ensemble = np.load(gt_transition_ensemble_file)

    n_ref_samples = 1000
    traj_len = 10

    # Discretize the interpolation trajectory based on the reference cluster centers
    cluster_assignments, transformed_samples = discretize_trajectory(
        sampled_mol, tic_evaluator, kmeans_cluster_centers
    )

    if gen_mode == "iid":
        sampled_traj = cluster_assignments  # don't need to subsample
    elif gen_mode == "langevin":
        # Fit a MSM to the generated samples, using the reference cluster centers
        (
            prob_matrix,
            _,
            _,
            _,
        ) = dynamics_analysis(
            protein_name,
            "langevin",
            append_exp_name=None,
            num_clusters=20,
            subsample=subsample,
            gt_cluster_assignments=cluster_assignments,
            lagtime=200,  # every 200 ps to match the reference frequency
        )
        sampled_traj = sample_tp(prob_matrix, start, end, traj_len, n_ref_samples)
    else:  # interpolate or om_interpolate
        cluster_assignments = cluster_assignments.reshape(num_paths, -1)
        sampled_traj = cluster_assignments[
            :, :: math.ceil(cluster_assignments.shape[1] / (traj_len - 1))
        ]
        # add the last state to the end of the trajectory
        sampled_traj = np.concatenate(
            [sampled_traj, cluster_assignments[:, -1:]], axis=1
        )

    # Sample transition paths from the reference MSM
    ref_sampled_traj = sample_tp(gt_prob_matrix, start, end, traj_len, n_ref_samples)

    # Compute entropy of the sampled trajectories (proxy for diversity)
    entropy = None
    if "interpolate" in gen_mode:
        entropy = compute_shannon_entropy(sampled_traj)
    ref_entropy = compute_shannon_entropy(ref_sampled_traj)

    # Compute JSD between the state distributions of the reference and generated paths
    sampled_state_dist = np.array(
        [np.count_nonzero(sampled_traj == i) for i in range(20)]
    )
    sampled_state_dist = sampled_state_dist / sampled_state_dist.sum()
    ref_state_dist = np.array(
        [np.count_nonzero(ref_sampled_traj == i) for i in range(20)]
    )
    ref_state_dist = ref_state_dist / ref_state_dist.sum()
    jsd = jensenshannon(ref_state_dist, sampled_state_dist)

    # Compute the JSD restricted to the transition ensemble of the reference and generated paths (defined as committor probs between 0.45 and 0.55)
    bins_x = np.digitize(transformed_samples[:, 0], tic_evaluator.bin_edges_x)
    bins_y = np.digitize(transformed_samples[:, 1], tic_evaluator.bin_edges_y)
    bins_x = np.clip(bins_x, 0, tic_evaluator.bins - 1)
    bins_y = np.clip(bins_y, 0, tic_evaluator.bins - 1)
    bin_idx = bins_x * tic_evaluator.bins + bins_y

    transition_ensemble_mask = np.logical_and(
        bin_committor_probs[bin_idx] > 0.45, bin_committor_probs[bin_idx] < 0.55
    )
    transition_ensemble = transformed_samples[transition_ensemble_mask]
    transition_ensemble, _ = discretize_trajectory(
        transition_ensemble, tic_evaluator, kmeans_cluster_centers, transform=False
    )
    transition_state_dist = np.array(
        [np.count_nonzero(transition_ensemble == i) for i in range(20)]
    )
    transition_state_dist = transition_state_dist / transition_state_dist.sum()
    gt_transition_ensemble, _ = discretize_trajectory(
        gt_transition_ensemble, tic_evaluator, kmeans_cluster_centers, transform=False
    )
    ref_transition_state_dist = np.array(
        [np.count_nonzero(gt_transition_ensemble == i) for i in range(20)]
    )

    ref_transition_state_dist = (
        ref_transition_state_dist / ref_transition_state_dist.sum()
    )
    transition_jsd = jensenshannon(ref_transition_state_dist, transition_state_dist)

    # Compute the likelihood of the sampled trajectories under the reference MSM
    path_probabilities = None
    fraction_valid_paths = None
    if gen_mode != "iid":
        path_probabilities = get_tp_likelihood(sampled_traj, gt_prob_matrix).prod(-1)

        # Percentage of valid (non-zero probability) paths
        fraction_valid_paths = (
            path_probabilities[path_probabilities > 0].shape[0]
            / path_probabilities.shape[0]
        )

    # Visualize the model-produced interpolation along with a subset of 20 reference/generated paths
    free_energies, transition_rates, fraction_unphysical = get_tic_free_energy_plots(
        protein_name,
        gen_mode,
        append_exp_name,
        subsample,
        gen_paths=(
            kmeans_cluster_centers[sampled_traj[:20]]
            if "langevin" in gen_mode
            else None
        ),
        ref_paths=kmeans_cluster_centers[ref_sampled_traj[:20]],
        gif=True,
        window_size=window_size,
        num_paths=num_paths,
        ref_dihedrals=ref_dihedrals,
        ref_pwds=ref_pwds,
        log=log,
    )

    max_free_energies = np.array(
        [np.max(free_energy_profile) for free_energy_profile in free_energies]
    )

    # Save final metrics to a JSON file
    metrics = {
        "Max Free Energy (kBT) Mean: ": max_free_energies.mean(),
        "Max Free Energy (kBT) Std: ": max_free_energies.std(),
        "Fraction of Physical Paths: ": (
            1 - fraction_unphysical if fraction_unphysical is not None else None
        ),
        "Transition Rate Mean: ": transition_rates.mean(),
        "Transition Rate Std: ": (
            transition_rates.std() if "interpolate" in gen_mode else None
        ),
        "Path Probability Mean": (
            path_probabilities.mean() if path_probabilities is not None else None
        ),
        "Path Probability Std": (
            path_probabilities.std() if path_probabilities is not None else None
        ),
        "Fraction of Valid Paths": fraction_valid_paths,
        "Jensen-Shannon Divergence of State Distributions": jsd,
        "Jensen-Shannon Divergence of Transition Ensemble State Distributions": transition_jsd,
        "Transition Path Entropy (Diversity)": entropy,
        "Reference Transition Path Entropy (Diversity)": ref_entropy,
    }

    subsample_append = f"_subsample_{subsample}" if subsample != 0 else ""
    final_metrics_file = "final_metrics" + subsample_append + ".json"

    with open(join(eval_folder, final_metrics_file), "w") as f:
        json.dump(metrics, f, indent=4)

    if log:
        wandb.log(metrics)


def get_tic_free_energy_plots(
    protein_name,
    gen_mode,
    append_exp_name,
    subsample=0,
    gen_paths=None,
    ref_paths=None,
    window_size=7,
    gif=False,
    num_paths=8,
    ref_dihedrals=None,
    ref_pwds=None,
    log=False,
):
    """
    Produces a TIC plot of the samples generated by the model, along with a reference interpolation path if provided.
    Also produces a free energy curve along the generated interpolation path.
    If gif is set to True, it will create a GIF of the Onsager-Machlup optimization process.
    # TODO: cleanup so that this function just takes in a list of trajectories and produces the plots, instead of loading from disk
    """

    # Load data
    append_exp_name_str = "_" + append_exp_name if append_exp_name else ""
    eval_folder = (
        f"saved_models/{protein_name}/main_eval_output_{gen_mode}{append_exp_name_str}"
    )
    sample_path = Path(eval_folder, f"sample-{gen_mode}.pt")
    pdb_file = (
        f"datasets/folded_pdbs/{Molecules[protein_name.upper()].value}-0-c-alpha.pdb"
    )
    # Load sampled molecules
    sampled_mol = torch.load(sample_path)
    if subsample != 0:
        sampled_mol = sampled_mol[:subsample]
    n_atoms = sampled_mol.shape[1]

    # Load topology from pdb file
    topology = md.load(pdb_file).topology
    # print(f"Atoms: {[a for a in topology.atoms]}")

    start, end = CLUSTER_ENDPOINTS[protein_name]

    # Load pretrained committor model
    device = torch.device(torch.cuda.current_device())
    model = GraphTransformer(num_beads=n_atoms, hidden_nf=64, conservative=True)
    committor_model = CommittorNN(model)
    state_dict = torch.load(
        f"saved_models/{protein_name}/committor-model-{start}_{end}.pt"
    )
    committor_model.load_state_dict(state_dict.state_dict())
    committor_model.to(device)

    # store endpoints if interpolation is used
    if "interpolate" in gen_mode:
        endpoints = sampled_mol.reshape(num_paths, -1, n_atoms, 3)[
            :, [0, -1]
        ].numpy()  # [num_paths, 2, n_atoms, 3]

    # Initialize evaluator
    tic_evaluator = TicEvaluator(
        val_data=None,
        mol_name=protein_name,
        eval_folder=eval_folder,
        data_folder="datasets",
        folded_pdb_folder="datasets/folded_pdbs",
        bins=101,
        evalset="testset",
    )  # The evalset is the set we'll compare to in the next evaluation steps

    loop = [sampled_mol]
    # Load path along optimization if OM interpolation is used
    if gif and gen_mode == "om_interpolate":
        path_history = Path(eval_folder, f"path_history-{gen_mode}.pt")
        path_history = torch.load(path_history)
        loop = path_history

    # Compute and save reference TIC plot
    ref_fig = tic_evaluator._plot_tic(
        tic_evaluator.gt_prob,
        endpoints=endpoints if "interpolate" in gen_mode else None,
        gen_paths=gen_paths,
        ref_paths=ref_paths,
        file_name=join(tic_evaluator.plots_folder, "TICA_reference.png"),
        title="Reference testset",
        save_plot=True,
    )

    free_energies = []

    # Create unique timestamped folder (to avoid overwriting with concurrent runs)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    gif_folder = f"temp_gif_images_{timestamp}"
    os.makedirs(gif_folder, exist_ok=True)

    tic_paths = []  # To keep track of the TIC image paths for creating a GIF
    free_energy_paths = (
        []
    )  # To keep track of the free energy image paths for creating a GIF
    dihedral_hist_paths = (
        []
    )  # To keep track of the dihedral angle histograms for creating a GIF
    pwd_hist_paths = (
        []
    )  # To keep track of the pairwise distance histograms for creating a GIF
    transition_rate_paths = (
        []
    )  # To keep track of the transition rate box plots for creating a GIF

    for i, path in tqdm(enumerate(loop)):
        # Get samples TIC free energy landscape
        dihedrals, pwds = tic_evaluator.get_tic_features(
            path, tic_evaluator.folded, separate=True
        )

        sample_tic_features = np.hstack((dihedrals, pwds))
        transformed_samples = tic_evaluator.tica(sample_tic_features)

        # Plot dihedral angle histogram
        plt.figure()
        plt.hist(
            np.ravel(dihedrals), bins=100, density=True, label="Interpolation Path"
        )
        if ref_dihedrals is not None:
            plt.hist(
                np.ravel(ref_dihedrals),
                bins=100,
                density=True,
                alpha=0.5,
                label="Reference",
            )
        plt.legend()
        plt.title(f"Step {i}: Dihedral angular distribution function")

        plt.xlabel("Dihedral angle (radians)")
        plt.ylabel("Frequency")
        plt.ylim(0, 0.6)
        plt.show()
        file_name = join(gif_folder, f"dihedral_{i}.png")
        plt.savefig(file_name)
        plt.close()
        dihedral_hist_paths.append(file_name)

        # Plot pairwise distance histogram
        plt.figure()
        plt.hist(np.ravel(pwds), bins=100, density=True, label="Interpolation Path")
        if ref_pwds is not None:
            plt.hist(
                np.ravel(ref_pwds), bins=100, density=True, alpha=0.5, label="Reference"
            )
        plt.legend()
        plt.title(f"Step {i}: Pairwise distance distribution function")

        plt.xlabel("Pairwise distance (Angstroms)")
        plt.ylabel("Frequency")
        plt.ylim(0, 0.2)
        plt.show()
        file_name = join(gif_folder, f"pwd_{i}.png")
        plt.savefig(file_name)
        plt.close()
        pwd_hist_paths.append(file_name)

        # Find the bins of the samples
        bins_x = np.digitize(transformed_samples[:, 0], tic_evaluator.bin_edges_x)
        bins_y = np.digitize(transformed_samples[:, 1], tic_evaluator.bin_edges_y)
        # clip the bins to the maximum bin index
        bins_x = np.clip(bins_x, 0, tic_evaluator.bins - 1)
        bins_y = np.clip(bins_y, 0, tic_evaluator.bins - 1)

        # probabilities of the samples as a function of path position
        gt_probs = np.zeros((path.shape[0],))

        # probabilities of the samples as a function of TICA bins
        prob_samp = np.zeros((tic_evaluator.bins, tic_evaluator.bins))

        padding = window_size // 2
        # Iterate over path
        for t in range(path.shape[0]):
            # Get the bin indices
            x_bin = bins_x[t]
            y_bin = bins_y[t]

            if tic_evaluator.gt_prob[x_bin, y_bin] != 0:
                # Ground truth probability in this bin is non-zero
                gt_probs[t] = tic_evaluator.gt_prob[x_bin, y_bin]
                prob_samp[x_bin, y_bin] = tic_evaluator.gt_prob[x_bin, y_bin]

            else:
                # Define the window boundaries
                x_min = max(0, x_bin - padding)
                x_max = min(tic_evaluator.gt_prob.shape[0] - 1, x_bin + padding)
                y_min = max(0, y_bin - padding)
                y_max = min(tic_evaluator.gt_prob.shape[1] - 1, y_bin + padding)

                # Extract the window
                window = tic_evaluator.gt_prob[x_min : x_max + 1, y_min : y_max + 1]

                # Find the minimum non-zero probability in the window
                non_zero_probs = window[window > 0]

                if non_zero_probs.size > 0:
                    # Set the minimum non-zero value in gt_probs
                    gt_probs[t] = np.min(non_zero_probs)
                    prob_samp[x_bin, y_bin] = np.min(non_zero_probs)
                else:
                    # If no non-zero values found, set gt_probs to 0
                    gt_probs[t] = 0
                    prob_samp[x_bin, y_bin] = 0

        # Calculate and plot the TIC landscape
        file_name = join(gif_folder, f"TICA_sampled_{i}.png")
        tic_evaluator._plot_tic(
            prob_samp,
            endpoints=endpoints if "interpolate" in gen_mode else None,
            gen_paths=gen_paths,
            ref_paths=ref_paths,
            file_name=file_name,
            title="Samples",
            save_plot=True,
        )  # Save the plot

        tic_paths.append(file_name)

        device = torch.device(torch.cuda.current_device())

        norm_grads = []
        for x in path.split(256):
            x = (x - x.mean(1, keepdim=True)) / norm_stds[
                Molecules[protein_name.upper()]
            ]
            x = x.requires_grad_(True).to(device)
            h = torch.eye(x.shape[-2]).to(device)
            t = torch.zeros((x.shape[0],)).to(device)
            pred_prob = committor_model(x, h, t)
            grad_prob = torch.autograd.grad(
                outputs=pred_prob,  # [batch_size, ]
                inputs=x,  # [batch_size, n_nodes, 3]
                grad_outputs=torch.ones_like(pred_prob),
                retain_graph=True,  # Make sure the graph is not destroyed during training
                create_graph=True,  # Create graph for second derivative
                allow_unused=True,
            )[0].detach()
            norm_grads.append(grad_prob.reshape(x.shape[0], -1).norm(dim=1))

        transition_rates = torch.cat(norm_grads, dim=0).cpu().numpy().astype(np.float64)

        # Box plot of transition rates
        plt.figure()
        plt.boxplot(transition_rates)
        plt.ylim(1e-6, 1e-1)
        plt.yscale("log")
        plt.title(f"Step {i}: Transition rates")
        plt.ylabel("Transition rate / (kBT / gamma)")
        plt.show()
        file_name = join(gif_folder, f"transition_rates_{i}.png")
        plt.savefig(file_name)
        plt.close()
        transition_rate_paths.append(file_name)

        # Calculate and plot the free energy profile along the path
        free_energy_profile = -np.log(gt_probs + np.exp(-10))
        free_energies.append(free_energy_profile)
        plt.figure()
        # plot free energy profile of all paths
        for profile in torch.tensor(free_energy_profile).chunk(num_paths):
            plt.plot(profile)
        plt.ylim(-6, 11)
        plt.xlabel("Path Step")
        plt.ylabel("Free energy / kBT")
        plt.title(f"Step {i}: Transition free energy profile: {protein_name}")
        plt.axhline(10, color="red", linestyle="--", label="Zero Probability Threshold")
        plt.legend()
        plt.show()
        file_name = join(gif_folder, f"free_energy_{i}.png")
        plt.savefig(file_name)
        plt.close()
        free_energy_paths.append(file_name)

        fraction_unphysical = None
        if i == len(loop) - 1 and "interpolate" in gen_mode:
            # save final metrics
            pwds = pwds.reshape(num_paths, -1, pwds.shape[-1])
            pwd_mins = np.min(pwds, axis=(1, 2))
            path_is_unphysical = pwd_mins < 0.5
            fraction_unphysical = path_is_unphysical.sum() / path_is_unphysical.shape[0]

    # Create a GIF from the saved TICA images
    tica_gif_path = join(tic_evaluator.plots_folder, "tica_samples.gif")
    images = [Image.open(tic_path) for tic_path in tic_paths]

    # Save as GIF
    images[0].save(
        tica_gif_path,
        save_all=True,
        append_images=images[1:],
        optimize=False,
        duration=100,  # Duration for each frame in milliseconds
        loop=0,  # Loop forever
    )

    # Repeat for the free energy images
    free_energy_gif_path = join(tic_evaluator.plots_folder, "free_energy.gif")
    images = [Image.open(free_energy_path) for free_energy_path in free_energy_paths]

    # Save as GIF
    images[0].save(
        free_energy_gif_path,
        save_all=True,
        append_images=images[1:],
        optimize=False,
        duration=100,  # Duration for each frame in milliseconds
        loop=0,  # Loop forever
    )

    # Repeat for the transition rate box plots
    transition_rate_gif_path = join(tic_evaluator.plots_folder, "transition_rates.gif")
    images = [
        Image.open(transition_rate_path)
        for transition_rate_path in transition_rate_paths
    ]

    # Save as GIF
    images[0].save(
        transition_rate_gif_path,
        save_all=True,
        append_images=images[1:],
        optimize=False,
        duration=100,  # Duration for each frame in milliseconds
        loop=0,  # Loop forever
    )

    # Repeat for the dihedral angle histograms
    dihedral_hist_gif_path = join(tic_evaluator.plots_folder, "dihedral_hist.gif")
    images = [
        Image.open(dihedral_hist_path) for dihedral_hist_path in dihedral_hist_paths
    ]
    images[0].save(
        dihedral_hist_gif_path,
        save_all=True,
        append_images=images[1:],
        optimize=False,
        duration=100,  # Duration for each frame in milliseconds
        loop=0,  # Loop forever
    )

    # Repeat for the pairwise distance histograms
    pwd_hist_gif_path = join(tic_evaluator.plots_folder, "pwd_hist.gif")
    images = [Image.open(pwd_hist_path) for pwd_hist_path in pwd_hist_paths]
    images[0].save(
        pwd_hist_gif_path,
        save_all=True,
        append_images=images[1:],
        optimize=False,
        duration=100,  # Duration for each frame in milliseconds
        loop=0,  # Loop forever
    )

    # Save the GIFs to the wandb run
    if log:
        wandb.log(
            {
                "Reference TICA": wandb.Image(
                    join(tic_evaluator.plots_folder, "TICA_reference.png")
                ),
                "TICA Samples": wandb.Image(tica_gif_path),
                "Free Energy Profiles": wandb.Image(free_energy_gif_path),
                "Transition Rates": wandb.Image(transition_rate_gif_path),
                "Dihedral Angle Histograms": wandb.Image(dihedral_hist_gif_path),
                "Pairwise Distance Histograms": wandb.Image(pwd_hist_gif_path),
            }
        )

    # Remove the temporary image files
    for image_path in (
        tic_paths
        + free_energy_paths
        + dihedral_hist_paths
        + pwd_hist_paths
        + transition_rate_paths
    ):
        os.remove(image_path)

    # Delete the gif folder
    os.rmdir(gif_folder)

    return free_energies, transition_rates, fraction_unphysical


def dynamics_analysis(
    protein_name,
    gen_mode,
    append_exp_name,
    num_clusters=None,
    subsample=None,
    gt_traj=None,
    gt_cluster_assignments=None,
    lagtime=1,
):
    """
    Analyze the dynamics of a set of samples.
    Create a Markov State Model (MSM) by clustering the samples in TIC-space and counting the transitions between clusters.
    Returns the transition probability matrix and the cluster centers.
    """

    # Load data
    if num_clusters is None:
        num_clusters = num_clusters_per_protein[protein_name]

    # Inferred
    append_exp_name_str = "_" + append_exp_name if append_exp_name else ""

    if gt_traj is None:
        eval_folder = f"saved_models/{protein_name}/main_eval_output_{gen_mode}{append_exp_name_str}"
        sample_path = Path(eval_folder, f"sample-{gen_mode}.pt")

        try:
            # Load sampled molecules
            sampled_mol = torch.load(sample_path)
        except FileNotFoundError:
            raise RuntimeError(
                f"File not found: {sample_path}. Have you run Langevin simulations for {protein_name}?"
            )
    else:
        eval_folder = "evaluate/saved_references"
        sampled_mol = torch.tensor(gt_traj)

    pdb_file = (
        f"datasets/folded_pdbs/{Molecules[protein_name.upper()].value}-0-c-alpha.pdb"
    )

    if subsample != 0:
        sampled_mol = sampled_mol[:subsample]

    n_atoms = sampled_mol.shape[1]

    # Load topology from pdb file
    topology = md.load(pdb_file).topology

    # Since we need to do K-means clustering in TIC-space, we will transform the samples first
    # (this code is the same as in the "TIC analysis" section)

    # Initialize TIC evaluator
    tic_evaluator = TicEvaluator(
        val_data=None,
        mol_name=protein_name,
        eval_folder=eval_folder,
        data_folder="datasets",
        folded_pdb_folder="datasets/folded_pdbs",
        bins=101,
        evalset="testset",
    )  # The evalset is the set we'll compare to in the next evaluation steps

    # Get samples TIC free energy landscape
    dihedrals, pwds = tic_evaluator.get_tic_features(
        sampled_mol, tic_evaluator.folded, separate=True
    )

    sample_tic_features = np.hstack((dihedrals, pwds))
    transformed_samples = tic_evaluator.tica(sample_tic_features)

    if gt_cluster_assignments is None:
        # K-means clustering
        kmeans = MiniBatchKMeans(
            n_clusters=num_clusters,
            max_iter=0,
            batch_size=64,
            init_strategy="kmeans++",
            n_jobs=16,
            tolerance=1e-7,
        )

        assignments = kmeans.fit_transform(transformed_samples)
    else:
        assignments = gt_cluster_assignments

    # Create MSM with 20 states
    count_matrix = TransitionCountEstimator.count(
        count_mode="sliding", dtrajs=[assignments.astype("int")], lagtime=lagtime
    )
    count_matrix = normalize(count_matrix, axis=1, norm="l1")

    # TODO: this should only be done for the reference MSM

    if gt_traj is not None:
        start_cluster_idx, end_cluster_idx = find_min_flux_states(count_matrix)
        np.save(
            f"./evaluate/saved_references/saved_cluster_endpoints_{protein_name.upper()}.npy",
            np.array([start_cluster_idx, end_cluster_idx]),
        )
        # Also save the transition matrix
        np.save(
            f"./evaluate/saved_references/saved_transition_matrix_{protein_name.upper()}.npy",
            count_matrix,
        )

    # count_matrix = make_reversible(count_matrix)

    # # Coarse-grain the MSM to 10 states
    # pcca_msm = pcca(count_matrix, 10)

    if gt_cluster_assignments is not None:
        kmeans_cluster_centers = None
    else:
        kmeans_cluster_centers = kmeans._model.cluster_centers

    if gt_traj is not None:
        # Save the cluster centers for the reference simulation
        if kmeans_cluster_centers is not None:
            np.save(
                f"./evaluate/saved_references/saved_cluster_centers_{protein_name.upper()}.npy",
                kmeans_cluster_centers,
            )

        # Save the dihedrals and pairwise distances for the reference simulation
        np.save(
            f"./evaluate/saved_references/saved_dihedrals_{protein_name.upper()}.npy",
            dihedrals,
        )
        np.save(
            f"./evaluate/saved_references/saved_pwds_{protein_name.upper()}.npy",
            pwds,
        )

    return count_matrix, kmeans_cluster_centers, dihedrals, pwds


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--protein_name",
        type=str,
        default="chignolin",
        help="Name of the protein to evaluate",
    )
    parser.add_argument(
        "--gen_mode",
        type=str,
        default="om_interpolate",
        help="Generation mode (iid, langevin, interpolate, om_interpolate)",
    )
    parser.add_argument(
        "--append_exp_name",
        type=str,
        default=None,
        help="Append experiment name to the saved model folder",
    )

    parser.add_argument(
        "--subsample",
        type=int,
        default=0,
        help="First n samples to evaluate (0 means all samples)",
    )

    parser.add_argument(
        "--disable_logging", action="store_true", help="Don't log to wandb"
    )

    args = parser.parse_args()

    evaluate_fastfolders(
        args.protein_name,
        args.gen_mode,
        args.append_exp_name,
        args.subsample,
        log=not args.disable_logging,
    )
